# Generated by Django 4.1.7 on 2023-02-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='typ',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
